[workspace]
resolver = "2"
members = ["easytier",  "easytier-gui/src-tauri"]
default-members = [ "easytier" ]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
